### ISSUE TITLE
Support DNS-01

### ISSUE THREAD

**Issue by RemiDesgrange** [sozu-proxy/sozu-acme#6]
Since this repo is really new. 

Will DNS-01 method supported ? Even if the certificate is really long to obtain. For example on OVH DNS, you need 30 sec sleep before saying to let's `Hey ok, you can try validate against the DNS TXT record`. I think DNS is more suitable for large deployment. 
The problem is that you need to put a pre-hook and post-hook in order to do that, which is not really a great design...

**Comment by Geal** [comment]
the DNS check is not really suited for this tool, since it would require driving a DNS server somewhere or talking to the API of the DNS provider. It's really easy with sozu to create and route an application on the fly, hence the design of that tool.
On larger deployments, people would probably roll their own version.
